import { useEffect, useState } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import "../styles/Certificates.css"

function Certificates() {
  const [certs, setCerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const fetchCertificates = async () => {
      try {
        const user = JSON.parse(
          localStorage.getItem("user")
        );

        const email =
          user?.email;

        const res = await axios.get(
          `${process.env.REACT_APP_API_URL}/api/certificates/${email}`
        );

        setCerts(res.data);
      } catch (err) {
        console.error(err);
        setError("Failed to load certificates");
      } finally {
        setLoading(false);
      }
    };

    fetchCertificates();
  }, []);

  const downloadPDF = (cert) => {
    const doc = new jsPDF("landscape");

    // Border
    doc.setDrawColor(0);
    doc.setLineWidth(1);
    doc.rect(10, 10, 277, 190);

    // LMS Name
    doc.setFontSize(28);
    doc.setFont("helvetica", "bold");
    doc.text(
      "LMS PLATFORM",
      148,
      30,
      { align: "center" }
    );

    // Certificate Title
    doc.setFontSize(30);
    doc.text(
      "CERTIFICATE OF COMPLETION",
      148,
      50,
      { align: "center" }
    );

    // Body
    doc.setFontSize(16);
    doc.setFont("helvetica", "normal");
    doc.text(
      "This is to certify that",
      148,
      75,
      { align: "center" }
    );

    // Student Name
    doc.setFontSize(28);
    doc.setFont("helvetica", "bold");
    doc.text(
      cert.userName || "Student Name",
      148,
      95,
      { align: "center" }
    );

    // Completion Text
    doc.setFontSize(16);
    doc.setFont("helvetica", "normal");
    doc.text(
      "has successfully completed the course",
      148,
      115,
      { align: "center" }
    );

    // Course Name
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text(
      cert.courseTitle || "Course Name",
      148,
      135,
      { align: "center" }
    );

    // Date
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Date: ${new Date(
        cert.completedAt
      ).toDateString()}`,
      20,
      170
    );

    // Certificate ID
    doc.text(
      `Certificate ID: ${cert._id?.slice(-8) || "N/A"}`,
      20,
      180
    );

    // Signature Line
    doc.line(210, 160, 270, 160);

    doc.text(
      "Authorized Signature",
      240,
      170,
      { align: "center" }
    );

    // Footer
    doc.setFontSize(10);
    doc.text(
      "Generated by LMS Platform",
      148,
      190,
      { align: "center" }
    );

    doc.save(
      `${cert.courseTitle || "Course"}_certificate.pdf`
    );
  };

  if (loading) {
    return <h2>Loading certificates...</h2>;
  }

  if (error) {
    return <h2>{error}</h2>;
  }

  return (
    <div className="certificates-container">
      <h2 className="certificates-title">
        🎓 Your Certificates
      </h2>

      {certs.length === 0 ? (
        <div className="empty-certificates">
          No certificates found.
        </div>
      ) : (
        <div className="certificates-grid">

          {certs.map((cert, i) => (
            <div
              key={i}
              className="certificate-card"
            >

              <div className="certificate-header">
                <span className="certificate-icon">
                  🏆
                </span>

                <div className="certificate-course">
                  {cert.courseTitle}
                </div>
              </div>

              <div className="certificate-info">
                <p>
                  <strong>Date:</strong>{" "}
                  {new Date(
                    cert.completedAt
                  ).toDateString()}
                </p>

                <p>
                  <strong>Student:</strong>{" "}
                  {cert.userName}
                </p>

                <p>
                  <strong>ID:</strong>{" "}
                  {cert._id?.slice(-8)}
                </p>
              </div>

              <button
                className="download-btn"
                onClick={() =>
                  downloadPDF(cert)
                }
              >
                📥 Download Certificate
              </button>

            </div>
          ))}

        </div>
      )}
    </div>
  );
}

export default Certificates;